template: |
  ### Don't forget to prepare the release:

  - Bump the version number in ll-voordemensen.php
  - Build CSS and JS with `npm run build`
  - Generate translations with `composer run make-pot`

  ## What’s Changed

  $CHANGES
