name: Build release package
on:
  push:
    branches:
      - asset_build

jobs:
  php:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - name: Setup WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
      - name: Generate debugging log
        run: |
          echo 'PHP Version:'
          php --version
          echo 'PHP Modules:'
          php -m
          echo 'Composer:'
          composer --version
          echo 'NPM:'
          npm -v
          echo 'Node:'
          node -v
          echo 'WP-CLI:'
          wp --info
      - name: Checkout plugin repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install composer dependencies (excluding dev)
        run: |
          composer install --prefer-dist --no-suggest --no-dev --optimize-autoloader --ignore-platform-reqs
      - name: Generate translations
        run: |
          composer run make-pot
      - name: Clean install NPM dependencies
        run: |
          npm ci
      - name: Build frontend assets
        run: |
          npm run build
      - name: Remove source files
        run: |
          rm -rf 7.3linux.sh
          rm -rf development
          rm -rf node_modules
          rm -rf src
          rm -rf .editorconfig
          rm -rf .gitignore
          rm -rf .eslintrc
          rm -rf .stylelintignore
          rm -rf .stylelintrc.json
          rm -rf auth.json
          rm -rf composer.*
          rm -rf docker-compose.yml
          rm -rf package-lock.json
          rm -rf package.json
          rm -rf phpcs.xml.dist
          rm -rf psalm-autoloader.php
          rm -rf psalm.baseline.xml
          rm -rf psalm.xml.dist
          rm -rf webpack.*
      - name: Commit all changes
        run: |
          git config --global user.email "bot-tank-top+jungle@level-level.com"
          git config --global user.name "[BOT] Tanktop Jungle"
          git add -A --force dist/
          git add -A --force languages/
          git commit -m "Asset build" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main-build
          force: true
