name: Build & test

on: [push]

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: wordpress
          MYSQL_DATABASE: wordpress
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, dom, simplexml
          tools: wp
      - uses: actions/checkout@v2
        with:
          path: wp-content/plugins/ll-voordemensen
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
      - name: Composer build
        run: |
          ls -lsah
          cd wp-content/plugins/ll-voordemensen
          composer config http-basic.${{ secrets.SATIS_DOMAIN }} "${{ secrets.SATIS_USERNAME }}" "${{ secrets.SATIS_PASSWORD }}"
          composer install --prefer-dist --no-suggest
        env:
          SATIS_DOMAIN: ${{ secrets.SATIS_DOMAIN }}
          SATIS_USERNAME: ${{ secrets.SATIS_USERNAME }}
          SATIS_PASSWORD: ${{ secrets.SATIS_PASSWORD }}
      - name: test:composer
        run: |
          cd wp-content/plugins/ll-voordemensen
          composer run test:composer
      - name: test:phpcs
        run: |
          cd wp-content/plugins/ll-voordemensen
          composer run test:phpcs
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Download & configure WP
        run: |
          wp core download --allow-root --skip-content
          wp config create --allow-root --dbname=wordpress --dbuser=root --dbpass=wordpress --dbhost=127.0.0.1:${{ job.services.mysql.ports['3306'] }}
          wp core install --allow-root  --url=localhost --title=Test --admin_user=admin --admin_password=password --admin_email=test@test.test
          wp plugin activate ll-voordemensen --allow-root
      - name: test:psalm
        run: |
          cd wp-content/plugins/ll-voordemensen
          composer run test:psalm
      - name: test:docs
        run: |
          cd wp-content/plugins/ll-voordemensen
          composer run test:docs
  npm-project:
    name: NPM project test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: wp-content/plugins/ll-voordemensen
      - name: Clean install dependencies
        run: |
          cd wp-content/plugins/ll-voordemensen
          npm ci
      - name: Lint
        run: |
          cd wp-content/plugins/ll-voordemensen
          npm run lint
      - name: Build
        run: |
          cd wp-content/plugins/ll-voordemensen
          npm run build
