name: Build & test

on: [push]

jobs:
  php:
    name: PHP test
    runs-on: ubuntu-latest
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@1.3.7
        with:
          php-version: 7.3
      - uses: actions/checkout@v2
        with:
          path: wp-content/plugins/ll-voordemensen
      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
      - name: Composer build
        run: |
          ls -lsah
          cd wp-content/plugins/ll-voordemensen
          composer config http-basic.${{ secrets.SATIS_DOMAIN }} "${{ secrets.SATIS_USERNAME }}" "${{ secrets.SATIS_PASSWORD }}"
          composer install --prefer-dist --no-suggest
        env:
          SATIS_DOMAIN: ${{ secrets.SATIS_DOMAIN }}
          SATIS_USERNAME: ${{ secrets.SATIS_USERNAME }}
          SATIS_PASSWORD: ${{ secrets.SATIS_PASSWORD }}
      - name: test:composer
        run: |
          cd wp-content/plugins/ll-voordemensen
          composer run test:composer
      - name: test:phpcs
        run: |
          cd wp-content/plugins/ll-voordemensen
          composer run test:phpcs
      - name: test:docs
        run: |
          cd wp-content/plugins/
          composer run test:docs
